/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author kritimakhatri
 */
public class LogoutScreen extends javax.swing.JInternalFrame {

    /**
     * Creates new form LogoutScreen
     */
    public LogoutScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMenu = new javax.swing.JPanel();
        Class = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1060, 650));

        PanelMenu.setBackground(new java.awt.Color(0, 0, 0));
        PanelMenu.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        PanelMenu.setPreferredSize(new java.awt.Dimension(250, 600));
        PanelMenu.setLayout(null);

        Class.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        Class.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/password c.png"))); // NOI18N
        Class.setText("Change password");
        Class.setBorder(null);
        Class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassActionPerformed(evt);
            }
        });
        PanelMenu.add(Class);
        Class.setBounds(320, 110, 162, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/FrameBG.png"))); // NOI18N
        PanelMenu.add(jLabel1);
        jLabel1.setBounds(0, 0, 1040, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassActionPerformed

        //        new OpenRoom().setVisible(true);
    }//GEN-LAST:event_ClassActionPerformed

    private void btnNoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoticeActionPerformed
       JOptionPane.showConfirmDialog(null, "Are you sure you want to Logout?","Log Out",JOptionPane.YES_NO_OPTION);
        int result = 0;
       if(result == JOptionPane.YES_OPTION){
//           new LoginScreen.setVisible(true);
       }else if (result == JOptionPane.NO_OPTION){
       this.dispose();
       }
        

//int result = JOptionPane.showConfirmDialog(frame,"Sure? You want to exit?", "Swing Tester",
//               JOptionPane.YES_NO_OPTION,
//               JOptionPane.QUESTION_MESSAGE);
//            if(result == JOptionPane.YES_OPTION){
//               label.setText("You selected: Yes");
//            }else if (result == JOptionPane.NO_OPTION){
//               label.setText("You selected: No");
//            }else {
//               label.setText("None selected");
//            }
//         }
//      });
//       
    }//GEN-LAST:event_btnNoticeActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
//        jDesktopPane1.removeAll();
//        noticepanel.removeAll();
//        jDesktopPane1.add(jPanel1);
//        jDesktopPane1.add(noticepanel);
//        jDesktopPane1.add(Profile);
//        jDesktopPane1.add(jPanel4);
//        jDesktopPane1.show();       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Class;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
